### ISSUE TITLE
Load Failed

### ISSUE THREAD

**Issue by reimannsum** [TehPers/StardewValleyMods#28]
https://smapi.io/log/9d6fc63a21444d52aed6971ff32b919c
[22:34:13 ERROR Teh's Fishing Overhaul] Mod crashed on entry and might not work correctly. Technical details:
System.MissingMethodException: Method not found: 'TehPers.Core.Json.IJsonApi TehPers.Core.Json.Extensions.GetJsonApi(TehPers.Core.ITehCoreApi)'.
   at TehPers.FishingOverhaul.ModFishing.LoadConfigs()
   at TehPers.FishingOverhaul.ModFishing.Entry(IModHelper helper) in C:\sdv_mods\My_FishingOverhaul\TehPers.FishingOverhaul\Configs\ConfigMain.cs:line 16
   at StardewModdingAPI.Framework.SCore.LoadMods(IModMetadata[] mods, JsonHelper jsonHelper, ContentCoordinator contentCore, ModDatabase modDatabase) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SCore.cs:line 1410
[22:34:13 TRACE SMAPI]    Found mod-provided API (TehPers.FishingOverhaul.FishingApi).

**Comment by noswanson1982** [comment]
I am having the same issue.  I closed my issue and suggested merging with yours.

**Comment by TehPers** [comment]
Thank you for opening this issue. I was taking a break from working on my mods at the time this was opened, and now this should be fixed after the rewrite of TehCore.
