### ISSUE TITLE
Unable to run (unofficial patch version)

### ISSUE THREAD

**Issue by noswanson1982** [TehPers/StardewValleyMods#29]
I am getting this in the SMAPI log:

[Teh's Fishing Overhaul] Mod crashed on entry and might not work correctly. Technical details:
System.MissingMethodException: Method not found: 'TehPers.Core.Json.IJsonApi TehPers.Core.Json.Extensions.GetJsonApi(TehPers.Core.ITehCoreApi)'.
   at TehPers.FishingOverhaul.ModFishing.LoadConfigs()
   at TehPers.FishingOverhaul.ModFishing.Entry(IModHelper helper) in C:\sdv_mods\My_FishingOverhaul\TehPers.FishingOverhaul\Configs\ConfigMain.cs:line 16
   at StardewModdingAPI.Framework.SCore.LoadMods(IModMetadata[] mods, JsonHelper jsonHelper, ContentCoordinator contentCore, ModDatabase modDatabase) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SCore.cs:line 1447

I did add the Teh's Core Mod thinking that might be affecting it, to no avail.  Is there something else I'm missing?

Thanks

**Comment by noswanson1982** [comment]
You can go ahead and merge mine with #28 .  They are the same issue.  Thanks.
